spring.application.name=storeMVC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=creator
spring.datasource.password=1111


spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.user=creator
spring.liquibase.password=1111
